source 'https://rubygems.org'
ruby '2.1.1'

gem 'rails', '4.1.1'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'bcrypt', '~> 3.1.7'
gem 'puma'
gem 'bootstrap-sass'
gem 'jquery-easing-rails'
gem 'mocha', git: 'git://github.com/freerange/mocha.git'
gem 'omniauth'
gem 'omniauth-dropbox-oauth2'
gem 'dropbox-sdk'
